services:
  mysql-master:
    build: ./master
    container_name: mysql-master
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - master_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 2s
      retries: 30

  mysql-replica:
    build: ./replica
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - replica_data:/var/lib/mysql
    depends_on:
      mysql-master:
        condition: service_healthy
      
volumes:
  master_data:
  replica_data:
