services:
  mysql-master:
    build: .
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db
    volumes:
      - master-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  master-data:
